name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  PROGRESS_NO_TRUNC: 1
  cache-name: docker-cache-5

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Use cached docker directory
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/docker_cache
          # Always want a cache miss on the first build of the day, which should be the scheduled
          # overnight one. Proves the build works from scratch, and gives you a nice clean cache to
          # work with each day.
          key: ${{ env.cache-name }}_${{ steps.date.outputs.date }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}_${{ steps.date.outputs.date }}-

      # Allow us to build multi-arch images
      - name: Set up Docker Buildx
        run: ./.github/setup-buildx.sh

      - name: Restore docker from cache
        run: .github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar

      - name: Build
        run: ./.github/ci-build.sh ghcr.io/wiremock/wiremock-studio:${{ github.sha }}

      - name: Prepare cached docker directory
        run: .github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache/cache.tar
