name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - run: env
      - name: Try and hit the cache myself...
        run: |
          curl -v \
            -H 'User-Agent: actions/cache' \
            -H 'Accept: application/json;api-version=6.0-preview.1' \
            -H "Authorization: Bearer $ACTIONS_RUNTIME_TOKEN" \
            "${ACTIONS_CACHE_URL}_apis/artifactcache/cache?keys=**-5cd6b27b51af611b66c925b48c66c165f2f94fac&version="

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: cached.txt
          key: mycache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            **-${{ github.sha }}
            mycache-${{ github.ref }}-
            mycache-

      - name: update cache
        run: |
          touch cached.txt
          echo "Initial state of cached.txt:"
          cat cached.txt
          echo ${{ github.ref }}-${{ github.sha }}-${{ github.run_number }} >> cached.txt
          echo "Updated state of cached.txt:"
          cat cached.txt

      - name: only if a tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo 'Got tag ${{github.ref_name}}' && cat cached.txt
