name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - run: mvn --version
      - run: cat ~/.m2/settings.xml
