name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use cached docker directory
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/docker_cache
          key: mycache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            **-${{ github.sha }}
            mycache-${{ github.ref }}-
            mycache-

      # Caching the entire docker dir is quite extreme. May stop being necessary with https://github.com/moby/buildkit/issues/1512
      - name: Restore docker from cache
        run: .github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar

      - name: update cache
        run: |
          if ! docker image inspect cached >/dev/null 2>&1; then docker pull alpine && docker tag alpine cached; fi
          docker run --name altered cached sh -c 'touch cached.txt && \
            echo "Initial state of cached.txt:" && \
            cat cached.txt && \
            echo ${{ github.ref }}-${{ github.sha }}-${{ github.run_number }} >> cached.txt && \
            echo "Updated state of cached.txt:" && \
            cat cached.txt'
  
          docker commit altered cached
          docker rm altered

      - name: Prepare cached docker directory
        run: .github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache
