name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - id: date
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Prepare maven repo credentials
        if: github.ref_name == 'explore-gradle'
        run: |
          touch wiremock-studio-ui.jar
          mkdir ~/.m2
          echo '<servers>
            <server>
              <id>wiremock.studio</id>
              <username>${{ secrets.MAVEN_REPO_USERNAME }}</username>
              <password>${{ secrets.MAVEN_REPO_PASSWORD }}</password>
            </server>
          </servers>
          ' > ~/.m2/settings.xml

      - run: >-
          mvn deploy:deploy-file
          -Durl=https://maven.pkg.github.com/wiremock/wiremock-studio
          -DrepositoryId=wiremock.studio
          -Dfile=wiremock-studio-ui.jar
          -DgroupId=org.wiremock
          -DartifactId=wiremock-studio-ui
          -Dversion=0.1.0-$(date +%s)

