name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: cached.txt
          key: mycache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            **-${{ github.sha }}
            mycache-${{ github.ref }}-
            mycache-

      - name: update cache
        run: |
          touch cached.txt
          echo "Initial state of cached.txt:"
          cat cached.txt
          echo ${{ github.ref }}-${{ github.sha }}-${{ github.run_number }} >> cached.txt
          echo "Updated state of cached.txt:"
          cat cached.txt
