name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - uses: gradle/gradle-build-action@v2
      - run: cat ~/.gradle/gradle.properties
