name: WireMock Studio Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: fake jar
        run: touch wiremock-studio-ui.jar

      - name: Prepare maven repo credentials
        run: |
          mkdir ~/.m2
          echo '<servers>
            <server>
              <id>wiremock.studio</id>
              <username>$GITHUB_ACTOR</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
          ' > ~/.m2/settings.xml

#      - name: Push wiremock-studio-ui.jar to maven repo
#        run: >-
#          mvn deploy:deploy-file
#          -Durl=https://maven.pkg.github.com/wiremock/wiremock-studio
#          -DrepositoryId=wiremock.studio
#          -Dfile=wiremock-studio-ui.jar
#          -DgroupId=org.wiremock
#          -DartifactId=wiremock-studio-ui
#          -Dversion=0.2.0-$(date +%s)

      - name: extract creds
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: settings.xml
          path: ~/.m2/settings.xml
